import { Page } from '@playwright/test';

import * as settings from '../config/settings';
import { test as base, expect } from '../src/fixtures';
import { LandingPage } from '../src/pages/LandingPage';
import { RegisterPage } from '../src/pages/RegisterPage';
import { BasePage } from '../src/pages/BasePage';
import {
  LoginPage,
  Login2FAPage,
  LoginToSPage,
  InstitutionalLoginPage,
  GenericInstitutionLoginPage,
  GenericInstitutionEmailLoginPage,
  GenericInstitutionUsernameLoginPage,
  GenericInstitutionIDLoginPage,
  ForgotPasswordPage,
  UnsupportedInstitutionLoginPage,
  GenericCASPage,
  oldLogin,
} from '../src/pages/LoginPage';

/** Port of `tests/test_login.py`. */

const test = base.extend<{ loginPage: LoginPage }>({
  loginPage: async ({ page }, use) => {
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await use(loginPage);
  },
});



/**
 * Logs in as a user with 2FA enabled and verifies the various elements on the 2FA
 * page. Does not complete login since Playwright has no way to access the one-time
 * pass code generated by the authentication provider.
 */
test.describe('2FA Page', { tag: '@core' }, () => {
  test.beforeEach(() => {
    test.skip(settings.PRODUCTION, 'Test should not run on production');
  });

  test('one-time password required error', async ({ page }) => {
    await oldLogin(page, settings.CAS_2FA_USER, settings.CAS_2FA_USER_PASSWORD);
    const twoFactorPage = await Login2FAPage.expectOn(page);
    await expect(twoFactorPage.usernameInput).toBeVisible();
    await expect(twoFactorPage.oneTimePasswordInput).toBeVisible();
    await twoFactorPage.verifyButton.click();
    await expect(twoFactorPage.loginErrorMessage).toHaveText('One-time password is required.');
  });

  test('invalid one-time password error', async ({ page }) => {
    await oldLogin(page, settings.CAS_2FA_USER, settings.CAS_2FA_USER_PASSWORD);
    const twoFactorPage = await Login2FAPage.expectOn(page);
    await twoFactorPage.oneTimePasswordInput.pressSequentially('999999');
    await twoFactorPage.verifyButton.click();
    await expect(twoFactorPage.loginErrorMessage).toHaveText(
      'The one-time password you entered is incorrect.'
    );
  });

  test('cancel link returns to landing page', async ({ page }) => {
    await oldLogin(page, settings.CAS_2FA_USER, settings.CAS_2FA_USER_PASSWORD);
    const twoFactorPage = await Login2FAPage.expectOn(page);
    await twoFactorPage.cancelLink.click();
    await LandingPage.expectOn(page);
  });

  test('need help link navigates to help site', async ({ page }) => {
    await oldLogin(page, settings.CAS_2FA_USER, settings.CAS_2FA_USER_PASSWORD);
    const twoFactorPage = new Login2FAPage(page);
    await twoFactorPage.needHelpLink.click();
    await page.waitForURL(/help\.osf\.io/, { timeout: 10000 });
  });
});

/**
 * Logs in as a user that has not accepted the OSF Terms of Service and verifies the
 * elements on the ToS acceptance page, without actually accepting (that would spoil
 * user setup data for future test runs).
 */
test.describe('Terms of Service Page', { tag: '@core' }, () => {
  test.beforeEach(() => {
    test.skip(settings.PRODUCTION, 'Test should not run on production');
  });

  test('continue button is disabled until checkbox is checked', async ({ page }) => {
    await oldLogin(page, settings.CAS_TOS_USER, settings.CAS_TOS_USER_PASSWORD);
    const tosPage = await LoginToSPage.expectOn(page);
    await expect(page.locator('#primarySubmitButton')).toBeDisabled();
    await tosPage.tosCheckbox.click();
    await expect(tosPage.continueButton).toBeEnabled();
  });

  test('terms of use link navigates to terms of use', async ({ page }) => {
    await oldLogin(page, settings.CAS_TOS_USER, settings.CAS_TOS_USER_PASSWORD);
    const tosPage = await LoginToSPage.expectOn(page);
    await tosPage.termsOfUseLink.click();
    await page.waitForURL(
      'https://github.com/CenterForOpenScience/cos.io/blob/master/TERMS_OF_USE.md',
      { timeout: 10000 }
    );
  });

  test('privacy policy link navigates to privacy policy', async ({ page }) => {
    await oldLogin(page, settings.CAS_TOS_USER, settings.CAS_TOS_USER_PASSWORD);
    const tosPage = await LoginToSPage.expectOn(page);
    await tosPage.privacyPolicyLink.click();
    await page.waitForURL(
      'https://github.com/CenterForOpenScience/cos.io/blob/master/PRIVACY_POLICY.md',
      { timeout: 10000 }
    );
  });

  test('cancel link returns to landing page', async ({ page }) => {
    await oldLogin(page, settings.CAS_TOS_USER, settings.CAS_TOS_USER_PASSWORD);
    const tosPage = await LoginToSPage.expectOn(page);
    await tosPage.cancelLink.click();
    await LandingPage.expectOn(page);
  });
});

/**
 * Generic CAS pages have no service in the login/logout url. Users shouldn't
 * normally reach these through the standard auth workflow, so these tests manually
 * manipulate urls to reach the pages and confirm they still work.
 */
test.describe('Generic CAS Pages', { tag: '@core' }, () => {
  test.beforeEach(async ({ throttleOnProd }) => {
    void throttleOnProd;
  });

  test('generic logged-in page shows login successful', async ({ page, mustBeLoggedIn }) => {
    void mustBeLoggedIn;
    await page.goto(`${settings.CAS_DOMAIN}/login`);
    const loggedInPage = await GenericCASPage.expectOn(page);
    await expect(loggedInPage.statusMessage).toHaveText('Login successful');
  });

  test('generic logged-out page shows logout successful', async ({ page }) => {
    await page.goto(`${settings.CAS_DOMAIN}/logout`);
    const loggedOutPage = await GenericCASPage.expectOn(page);
    await expect(loggedOutPage.statusMessage).toHaveText('Logout successful');
  });
});

/** Inline error messages on the CAS login page for invalid login data. */
test.describe('Login Errors', { tag: '@core' }, () => {
  test.beforeEach(async ({ throttleOnProd }) => {
    void throttleOnProd;
  });

  test('missing email shows required error', async ({ page, loginPage }) => {
    await page.waitForURL(/\/login/, { timeout: 10000 });
    await loginPage.submitButton.click();
    await expect(loginPage.loginErrorMessage.first()).toHaveText('Email is required.');
  });

  test('missing password shows required error', async ({ page, loginPage }) => {
    await page.waitForURL(/\/login/, { timeout: 10000 });
    await loginPage.usernameInput.pressSequentially('foo');
    await loginPage.submitButton.click();
    await expect(loginPage.loginErrorMessage).toHaveText('Password is required.');
  });

  test('invalid email and password shows incorrect error', async ({ page, loginPage }) => {
    await page.waitForURL(/\/login/, { timeout: 10000 });
    await loginPage.usernameInput.pressSequentially('foo');
    await loginPage.passwordInput.pressSequentially('foo');
    await loginPage.submitButton.click();
    await expect(loginPage.loginErrorMessage).toHaveText(
      'The email or password you entered is incorrect.'
    );
  });

  test('invalid password shows incorrect error', async ({ page, loginPage }) => {
    await page.waitForURL(/\/login/, { timeout: 10000 });
    await loginPage.usernameInput.pressSequentially(settings.USER_ONE);
    await loginPage.passwordInput.pressSequentially('foo');
    await loginPage.submitButton.click();
    await expect(loginPage.loginErrorMessage).toHaveText(
      'The email or password you entered is incorrect.'
    );
  });
});

/**
 * CAS custom exception pages share the CAS login page style/appearance. Some
 * require manipulating urls to reach, since they can't easily be triggered via UI.
 */
test.describe('Custom Exception Pages', { tag: '@core' }, () => {
  test.beforeEach(async ({ throttleOnProd }) => {
    void throttleOnProd;
  });

  test('service not authorized page', async ({ page }) => {
    await page.goto(`${settings.CAS_DOMAIN}/login?service=https://noservice.osf.io/`);
    const exceptionPage = await GenericCASPage.expectOn(page);
    await expect(exceptionPage.statusMessage).toHaveText('Service not authorized');
  });

  test('verification key login failed page', async ({ page }) => {
    await page.goto(
      `${settings.CAS_DOMAIN}/login?service=${settings.CAS_DOMAIN}/login/?next=` +
        `${settings.CAS_DOMAIN}/&username=${settings.USER_ONE}&verification_key=foo`
    );
    const exceptionPage = await GenericCASPage.expectOn(page);
    await expect(exceptionPage.statusMessage).toHaveText('Verification key login failed');
  });

  test('flow-less page not found page', async ({ page }) => {
    await page.goto(`${settings.CAS_DOMAIN}/nopath`);
    const exceptionPage = await GenericCASPage.expectOn(page);
    await expect(exceptionPage.statusMessage).toHaveText('Page Not Found');
  });

  test('account not confirmed page', async ({ page }) => {
    test.skip(settings.PRODUCTION, 'Test should not run on production');
    await oldLogin(page, settings.UNCONFIRMED_USER, settings.UNCONFIRMED_USER_PASSWORD);
    const exceptionPage = await GenericCASPage.expectOn(page);
    await expect(exceptionPage.statusMessage).toHaveText('Account not confirmed');
  });

  test('account disabled page', async ({ page }) => {
    test.skip(settings.PRODUCTION, 'Test should not run on production');
    await oldLogin(page, settings.DEACTIVATED_USER, settings.DEACTIVATED_USER_PASSWORD);
    const exceptionPage = await GenericCASPage.expectOn(page);
    await expect(exceptionPage.statusMessage).toHaveText('Account disabled');
  });
});

/** Try to verify a login page; return the verified page instance or false. */
async function tryLoginPage<T extends BasePage>(
  page: Page,
  PageClass: new (page: Page) => T
): Promise<T | false> {
  try {
    const instance = new PageClass(page);
    await instance.verify(settings.QUICK_TIMEOUT_MS);
    return instance;
  } catch {
    return false;
  }
}



test.describe('Institution Login Page', { tag: ['@smoke', '@core'] }, () => {
  const institutionTest = test.extend<{
    institutionLoginPage: InstitutionalLoginPage;
    institutionList: string[];
  }>({
    institutionLoginPage: async ({ page }, use) => {
      const institutionLoginPage = new InstitutionalLoginPage(page);
      await institutionLoginPage.goto();
      await use(institutionLoginPage);
    },
    institutionList: async ({ institutionLoginPage }, use) => {
      await use(await institutionLoginPage.dropdownOptions.allTextContents());
    },
  });

  institutionTest.beforeEach(async ({ throttleOnProd }) => {
    void throttleOnProd;
  });

  institutionTest('osf home link returns to landing page', async ({
    page,
    institutionLoginPage,
  }) => {
    await institutionLoginPage.osfHomeLink.click();
    await LandingPage.expectOn(page);
  });

  institutionTest("can't find institution link", async ({ page, institutionLoginPage }) => {
    await institutionLoginPage.cantFindInstitutionLink.click();
    await UnsupportedInstitutionLoginPage.expectOn(page);
  });

  institutionTest('need help link navigates to help site', async ({
    page,
    institutionLoginPage,
  }) => {
    await institutionLoginPage.needHelpLink.click();
    await page.waitForURL(/help\.osf\.io/, { timeout: 10000 });
  });

  institutionTest('COS footer link navigates to cos.io', async ({ page, institutionLoginPage }) => {
    await institutionLoginPage.cosFooterLink.click();
    await page.waitForURL('https://www.cos.io/', { timeout: 10000 });
  });

  institutionTest('terms of use footer link navigates to terms of use', async ({
    page,
    institutionLoginPage,
  }) => {
    await institutionLoginPage.termsOfUseFooterLink.click();
    await page.waitForURL(
      'https://github.com/CenterForOpenScience/cos.io/blob/master/TERMS_OF_USE.md',
      { timeout: 10000 }
    );
  });

  institutionTest('privacy policy footer link navigates to privacy policy', async ({
    page,
    institutionLoginPage,
  }) => {
    await institutionLoginPage.privacyPolicyFooterLink.click();
    await page.waitForURL(
      'https://github.com/CenterForOpenScience/cos.io/blob/master/PRIVACY_POLICY.md',
      { timeout: 10000 }
    );
  });

  institutionTest('status footer link navigates to status page', async ({
    page,
    institutionLoginPage,
  }) => {
    await institutionLoginPage.statusFooterLink.click();
    await page.waitForURL('https://status.cos.io/', { timeout: 10000 });
  });

  /**
   * Confirms that selecting each institution from the dropdown and clicking Sign In
   * actually navigates to a valid institution login page. Only runs in Production
   * since most institutions don't have working test environments.
   */
  institutionTest('individual institution login pages', async ({
    page,
    institutionLoginPage,
    institutionList,
  }) => {
    test.skip(!settings.PRODUCTION, 'Most Institution Logins only work in Production');

    const failedList: string[] = [];
    for (const institution of institutionList) {
      if (institution === 'Select institution') continue;

      await institutionLoginPage.institutionDropdown.selectOption({ label: institution });
      await page.waitForTimeout(1000);
      await institutionLoginPage.signInButtonInstitutions.click();

      let success = false;
      const pageClasses = [
        GenericInstitutionLoginPage,
        GenericInstitutionEmailLoginPage,
        GenericInstitutionUsernameLoginPage,
        GenericInstitutionIDLoginPage,
      ];
      for (const PageClass of pageClasses) {
        if (await tryLoginPage(page, PageClass)) {
          success = true;
          break;
        }
      }
      if (!success) failedList.push(institution);

      await institutionLoginPage.goto();
    }

    expect(failedList, `The following Institutions Failed: ${failedList}`).toHaveLength(0);
  });
});

test.describe('Login Page', { tag: ['@smoke'] }, () => {
  test.beforeEach(async ({ throttleOnProd }) => {
    void throttleOnProd;
  });

  test('institutional login shows a populated institution dropdown', async ({
    page,
    loginPage,
  }) => {
    await loginPage.selectInstitutionLogin();
    const institutionalLoginPage = await InstitutionalLoginPage.expectOn(page);
    expect(await institutionalLoginPage.dropdownOptions.count()).toBeGreaterThan(0);
  });

  test('orcid login button navigates to ORCID sign-in', { tag: '@core' }, async ({
    page,
    loginPage,
  }) => {
    await loginPage.orcidLoginButton.click();
    await page.waitForURL(/orcid\.org\/signin/, { timeout: 10000 });
    expect(page.url()).not.toContain('error');
  });

  test('osf home link returns to the landing page', async ({ page, loginPage }) => {
    // await loginPage.selectInstitutionLogin();
    await page.waitForURL(/\/login/, { timeout: 10000 });
    await loginPage.osfHomeLink.click();
    await LandingPage.expectOn(page);
  });

  test('sign up button navigates to register page', async ({ page }) => {
    const landingPage = await new LandingPage(page).goto();
    await landingPage.getStartedButton.click();
    await RegisterPage.expectOn(page);
  });

  test('reset password link navigates to forgot password page', async ({
    page,
    loginPage,
  }) => {
    await page.waitForURL(/\/login/, { timeout: 10000 });
    await loginPage.resetPasswordLink.click();
    await ForgotPasswordPage.expectOn(page);
  });

  test('need help link navigates to help site', async ({ page, loginPage }) => {
    await loginPage.selectInstitutionLogin();
    await page.waitForURL(/\/login/, { timeout: 10000 });
    await loginPage.needHelpLink.click();
    await page.waitForURL(/help\.osf\.io/, { timeout: 10000 });
  });

  test('COS footer link navigates to cos.io', async ({ page, loginPage }) => {
    await loginPage.cosFooterLink.click();
    await page.waitForURL('https://www.cos.io/', { timeout: 10000 });
  });

  test('terms of use footer link navigates to terms of use', async ({ page, loginPage }) => {
    await page.waitForURL(/\/login/, { timeout: 10000 });
    await loginPage.termsOfUseFooterLink.click();
    await page.waitForURL(
      'https://github.com/CenterForOpenScience/cos.io/blob/master/TERMS_OF_USE.md',
      { timeout: 10000 }
    );
  });

  test('privacy policy footer link navigates to privacy policy', async ({
    page,
    loginPage,
  }) => {
    await page.waitForURL(/\/login/, { timeout: 10000 });
    await loginPage.privacyPolicyFooterLink.click();
    await page.waitForURL(
      'https://github.com/CenterForOpenScience/cos.io/blob/master/PRIVACY_POLICY.md',
      { timeout: 10000 }
    );
  });

  test('status footer link navigates to status page', async ({ page, loginPage }) => {
    await page.waitForURL(/\/login/, { timeout: 10000 });
    await loginPage.statusFooterLink.click();
    await page.waitForURL('https://status.cos.io/', { timeout: 10000 });
  });
});
